#!/usr/bin/env bash

# Bootstrap an environment for hacking on YABSM. We are going to use
# Perl::Build to compile Perl version 5.16.3, set up App::plx to use the Perl we
# build, and then use plx to install all our dependencies into a local::lib with
# cpanm.
#
# Perl::Build    - https://metacpan.org/pod/Perl::Build
# App::plx       - https://metacpan.org/pod/App::plx
# App::cpanminus - https://metacpan.org/pod/App::cpanminus

set -e

SCRIPT=${0##*/}

USAGE=$(cat <<EOF
usage: $SCRIPT [OPTIONS]
Options are:
  -h            Show this help message.
  -d directory  Install Perl v5.16.3 to DIRECTORY. By default installs to 
                yabsm/perl-5.16.3.
  -s            Prevent passing --force flag to cpanm.
EOF
)

while [ -n "$1" ]; do
  opt=$1
  shift
  case $opt in
    -h)
      echo "$USAGE"
      exit 0
      ;;
    -d)
      PERL_BUILD_DIR="$1"
      shift
      ;;
    -s)
      CPANM_FORCE_FLAG=no
      ;;
    *)
      echo "$USAGE"
      exit 1
      ;;
  esac  
done

# Lets work from the yabsm root directory.
YABSM_ROOT=$(realpath "$(dirname "$(readlink -f "$0")")"/..)
cd "$YABSM_ROOT" || (echo "$SCRIPT: could not cd to '$YABSM_ROOT'" >&2 && exit 1)

# Build Perl v5.16.3 with Perl::Build.
PERL_BUILD_DIR=${PERL_BUILD_DIR:-"$YABSM_ROOT/perl-5.16.3"}
PERL_EXECUTABLE="$PERL_BUILD_DIR/bin/perl"
PERL_BUILD_COMMAND="curl -L https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build | perl - 5.16.3 $PERL_BUILD_DIR"
echo "$SCRIPT: executing: $PERL_BUILD_COMMAND"
eval "$PERL_BUILD_COMMAND"

# Install and initialize App::plx.

mkdir -p "$YABSM_ROOT/local/bin"
wget https://raw.githubusercontent.com/shadowcat-mst/plx/master/bin/plx-packed -O "$YABSM_ROOT/local/bin"
PLX_EXECUTABLE="$YABSM_ROOT/local/bin/plx"
chmod 0555 "$PLX_EXECUTABLE"
PLX_INIT_COMMAND="$PLX_EXECUTABLE --init $PERL_EXECUTABLE"
echo "$SCRIPT: executing: $PLX_INIT_COMMAND"
eval "$PLX_INIT_COMMAND"

# All modules we use that aren't built into Perl v5.16.3 must be specified in
# the $YABSM_ROOT/DEPENDENCIES file.
#
# We will use plx's cpanm to install all the dependencies to a local::lib in
# $YABSM_ROOT/local.

while read -r dep; do 
  YABSM_DEPENDENCIES="$YABSM_DEPENDENCIES $dep"
done <<< "$(sed -e '/^$|#.*|[\t ]+/d' "$YABSM_ROOT/DEPENDENCIES")"

export PERL_CPANM_HOME="$YABSM_ROOT/.cpanm"

if [ no == $CPANM_FORCE_FLAG ]; then # use --force flag by default.
  CPANM_FORCE_FLAG=''
else
  CPANM_FORCE_FLAG='--force'
fi

INSTALL_DEPENDENCIES_COMMAND="$PLX_EXECUTABLE --cpanm -L local -v $CPANM_FORCE_FLAG -i $YABSM_DEPENDENCIES"
echo "$SCRIPT: executing: $INSTALL_DEPENDENCIES_COMMAND"
eval "$INSTALL_DEPENDENCIES_COMMAND"
