#!/usr/bin/env perl

# Use App::FatPacker::Simple to pack all of yabsm including its dependencies into one
# script. The end user will be given only the fatpacked script that is stripped
# of comments and pod by Perl::Tidy.

use strict;
use warnings;
use v5.16.3;

use Cwd qw/abs_path/;
use File::Basename qw/basename dirname/;
use File::Path qw(rmtree);

my $script = basename(__FILE__);
my $yabsm_root = dirname(abs_path(__FILE__ . '/..'));

chdir $yabsm_root;

my $plx = '';
# Default to a plx in $PATH
$plx = "$yabsm_root/local/bin/plx" if -x "$yabsm_root/local/bin/plx";
$plx = `sh -c 'command -v plx'` if `sh -c 'command -v plx'`;
chomp $plx;

my $fatpack = "$yabsm_root/local/bin/fatpack-simple";

my $local_lib = "$yabsm_root/local";

my $excluded = join ',', qw(Module::Build
                            CPAN::Meta
                            ok
                            PPI
                            JSON
                            App::Prove
                            App::FatPacker
                            TAP::Base
                            TAP::Parser
                            TAP::Object
                            TAP::Harness
                            TAP::Formatter
                            Test2::Event
                            Test2::API
                            Test2::Formatter
                            Test2::EventFacet
                            Test2::IPC
                            Test2::Hub
                            Test2::Util
                           );

my $yabsm_fatpacked = "$yabsm_root/export/yabsm.fatpack.pl";
my $yabsmd_fatpacked = "$yabsm_root/export/yabsmd.fatpack.pl";

my $fatpack_yabsm_cmd = "$plx --perl $fatpack -d $local_lib --shebang '#!/usr/bin/env perl' -o $yabsm_fatpacked $yabsm_root/src/yabsm.pl";
my $fatpack_yabsmd_cmd = "$plx --perl $fatpack -d $local_lib --shebang '#!/usr/bin/env perl' -o $yabsmd_fatpacked $yabsm_root/src/yabsmd.pl";

chdir "$yabsm_root/src";

say "$script: executing: $fatpack_yabsm_cmd";
0 == system($fatpack_yabsm_cmd) or die "$script: error: could not fatpack $yabsm_root/src/yabsm.pl\n";

say "$script: executing: $fatpack_yabsmd_cmd";
0 == system($fatpack_yabsmd_cmd) or die "$script: error: could not fatpack $yabsm_root/src/yabsmd.pl\n";

chmod 0755, $yabsm_fatpacked;
chmod 0755, $yabsmd_fatpacked;

rmtree "$yabsm_root/src/fatlib";

say 'all good';
