#!/usr/bin/env bash

# Use App::FatPacker to pack all of yabsm including its dependencies into one
# script. The end user will be given only the fatpacked script.

set -e

SCRIPT=${0##*/}

YABSM_ROOT=$(realpath "$(dirname "$(readlink -f "$0")")"/..)
SRC_DIR="$YABSM_ROOT"/src
EXPORT_DIR="$YABSM_ROOT"/export

# Lets work from the src directory.
cd "$SRC_DIR" || (echo "error: could not cd to dir '$SRC_DIR'" >&2 && exit 1)

FATPACK_EXECUTABLE="$YABSM_ROOT"/local/bin/fatpack
PLX_EXECUTABLE="$YABSM_ROOT"/local/bin/plx

FATPACK_COMMAND="$PLX_EXECUTABLE --perl $FATPACK_EXECUTABLE pack $YABSM_ROOT/src/yabsm.pl > $EXPORT_DIR/yabsm.fatpack.pl"
echo "$SCRIPT: executing: $FATPACK_COMMAND"
eval "$FATPACK_COMMAND"
