#!/usr/bin/env perl

#  Author:  Nicholas Hubbard
#  WWW:     https://github.com/NicholasBHubbard/yabsm
#  License: MIT

#  Interface for using cpanminus with plx.

use strict;
use warnings;
use v5.16.3;

use Cwd qw/abs_path/;
use File::Basename qw/basename dirname/;

my $script = basename(__FILE__);
my $yabsm_root = dirname(abs_path(__FILE__ . '/..'));

my $plx = `sh -c 'command -v plx'`
       || ( -x "$yabsm_root/local/bin/plx" && "$yabsm_root/local/bin/plx" )
       || die "$script: error: could not find a plx executable";

chomp $plx;

system("cd $yabsm_root ; PERL_CPANM_HOME=$yabsm_root $plx --cpanm -Llocal @ARGV");
