#!/usr/bin/env perl

#  Author:  Nicholas Hubbard
#  WWW:     https://github.com/NicholasBHubbard/yabsm
#  License: MIT

#  Interface for using cpanminus with plx.

use strict;
use warnings;
use v5.16.3;

use Cwd qw/abs_path/;
use File::Basename qw/basename dirname/;

my $SCRIPT_NAME = basename(__FILE__);

my $YABSM_ROOT = dirname(abs_path(__FILE__ . '/..'));

my $plx = `which plx 2>/dev/null`
       || ( -x "$YABSM_ROOT/local/bin/plx" && "$YABSM_ROOT/local/bin/plx" )
       || die "$SCRIPT_NAME: could not find a plx executable\n";

$plx =~ s/\s+//g;

system("cd $YABSM_ROOT ; PERL_CPANM_HOME=$YABSM_ROOT $plx --cpanm -Llocal @ARGV");
