#  Author:  Nicholas Hubbard
#  WWW:     https://github.com/NicholasBHubbard/yabsm
#  License: MIT

#  Write cronjobs that are generated by reading /etc/yabsm.conf to
#  /etc/crontab.

package Yabsm::Commands::UpdateEtcCrontab;

use strict;
use warnings;
use v5.16.3;

# located using lib::relative in yabsm.pl
use Yabsm::Base;
use Yabsm::Config;

use File::Copy 'move';

sub die_usage {
    die "usage: yabsm update-crontab\n";
}

sub main {

    die "yabsm: error: permission denied\n" if $<;

    die_usage() if @_;

    my $config_ref = Yabsm::Config::read_config();

    open (my $etc_crontab_fh, '<', '/etc/crontab')
      or die "yabsm: error: failed to open file '/etc/crontab'\n";

    open (my $tmp_fh, '>', '/tmp/yabsm-update-tmp')
      or die "yabsm: error: failed to open tmp file '/tmp/yabsm-update-tmp'\n";

    # rewrite non-yabsm data to the tmp file
    while (<$etc_crontab_fh>) {
	say $tmp_fh $_ unless /yabsm (incremental-backup|take-snap)/; 
    }

    # append the cronjob strings to $tmp file.
    say $tmp_fh $_ for Yabsm::Base::generate_cron_strings( $config_ref );

    # crontab files must end with a blank line.
    print $tmp_fh, "\n"; 

    close $etc_crontab_fh;
    close $tmp_fh;

    move '/tmp/yabsm-update-tmp', '/etc/crontab';

    return;
} 

1;
