#  Author:  Nicholas Hubbard
#  WWW:     https://github.com/NicholasBHubbard/yabsm
#  License: MIT

#  Write cronjobs that are generated by reading /etc/yabsm.conf to
#  /etc/crontab.

package Yabsm::Commands::UpdateEtcCrontab;

use strict;
use warnings;
use v5.16.3;

# located using lib::relative in yabsm.pl
use Yabsm::Base;
use Yabsm::Config;

use File::Temp 'tempfile';
use File::Copy 'copy';

sub die_usage {
    die "usage: yabsm update-crontab\n";
}

sub main {

    die "yabsm: error: permission denied\n" if $<;

    die_usage() if @_;

    my $config_ref = Yabsm::Config::read_config();

    open (my $etc_crontab_fh, '<', '/etc/crontab')
      or die "yabsm: error: failed to open file '/etc/crontab'\n";

    my ($tmp_fh, $tmp_filename) = tempfile(DIR => '/tmp', UNLINK => 1);

    # rewrite non-yabsm data to the tmp file
    while (<$etc_crontab_fh>) {
        say $tmp_fh $_ if $_ !~ /yabsm (take-snap|incremental-backup)/;
    }

    # Write new cronjobs
    say $tmp_fh $_ for Yabsm::Base::generate_cron_strings( $config_ref );

    # crontab file must end with a blank line
    print $tmp_fh "\n";

    copy $tmp_filename, '/etc/crontab';

    close $etc_crontab_fh;

    return;
} 

1;
