#!/usr/bin/env perl

#  Author: Nicholas Hubbard
#  Email:  nhub73@keemail.me
#  WWW:    https://github.com/NicholasBHubbard/yabsm
#
#  This script initializes yabsm. This script should be run by the
#  user after they clone the git repository, and can then be
#  discarded.

use strict;
use warnings;
use 5.010;

die "Permission denied\n" if $<;

die "[!] Perl version must be at least 5.10\n" if $] < 5.010000;

use FindBin '$Bin';
use File::Copy 'copy';

copy "$Bin/export/yabsmrc", '/etc/yabsmrc';
copy "$Bin/yabsm.fatpack.pl", '/usr/local/bin/yabsm';

chmod 0644, '/etc/yabsmrc';
chmod 0755, '/usr/local/bin/yabsm';

say 'all good';
