#!/usr/bin/env perl

#  Author: Nicholas Hubbard
#  Email:  nhub73@keemail.me
#  WWW:    https://github.com/NicholasBHubbard/yabsm
#
#  This script installs yabsm to the local machine. This script should
#  be run by the user after they clone the git repository. After
#  running this script the git repository may be removed.

use strict;
use warnings;
use v5.16.3;

die "error: permission denied\n" if $<;

die "error: your perl version '$]' is less than 5.16.3" if $] < 5.016003;

use FindBin '$Bin';
use File::Copy 'copy';

copy "$Bin/export/yabsmrc.example", '/etc/yabsmrc.example';
copy "$Bin/export/yabsm.fatpack.pl", '/usr/local/bin/yabsm';

chmod 0644, '/etc/yabsmrc';
chmod 0755, '/usr/local/bin/yabsm';

say 'all good';
