=pod

=head1 What is Yabsm?

Yabsm is a btrfs snapshot and backup management system that provides the 
following features.

=over 4

=item *

Takes readonly snapshots and performs remote and local incremental backups.

=item *

Seperates snapshots and backups into 5minute, hourly, daily, weekly, and monthly
timeframe categories

=item *

Cycles out old snapshots and backups on a per-timeframe basis

=item *

Provides a simple query language for locating snapshots and backups.

=back

=head1 Snapshots vs Backups

The difference between a snapshot and a backup can be a little confusing. 

When we talk about a snapshot we mean a read-only subvolume created with the
C<btrfs subvolume snapshot -r> command.

A backup is a snapshot that has been transferred to another btrfs filesystem via
a combination of C<btrfs send> and C<btrfs receive>.

L<btrfs snapshots|https://btrfs.readthedocs.io/en/latest/btrfs-subvolume.html#subvolume-and-snapshot>

L<btrfs send/receive|https://btrfs.readthedocs.io/en/latest/Send-receive.html>

=head1 Dependencies

=over 4

=item *

Perl

=item *

OpenSSH

=item *

btrfs-progs

=item *

sudo

=back

=head1 Installation

TODO

=head1 Starting the Yabsm Daemon

  TODO

=head1 Configuration

Yabsm in configured via the C</etc/yabsm.conf> file.

On installation this file will not exist, but there will be a file
C</etc/yabsmd.conf.example> that you can use to help you build your
configuration.

You can run the command C<yabsm config check> that will check your config and
output useful error messages to STDERR if there are any problems.

=head3 Configuration Grammar
    
You must specify a C<yabsm_dir> that yabsm will use for storing snapshots and 
using as a cache for holding objects needed for performing backups. Most commonly
this directory is C</.snapshots/yabsm>.

C<yabsm_dir=/.snapshots/yabsm>

There are 4 different configuration objects, =subvols=, =snaps=, =ssh_backups=,
and =local_backups=.

A =subvol= is the simplest configuration object, and is used to give a name to
a L<btrfs subvolume|https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Subvolumes> on your system. A subvol definition accepts one field called
=mountpoint= which takes a value that is a path to a subvolume.

#+BEGIN_SRC
subvol home_subvol {
    mountpoint=/home
}
#+END_SRC

A =snap= defines a

snap home_snap {
    subvol=home_subvol
    
    timeframes=hourly,daily
    
    hourly_keep=24 
    
    daily_keep=365
    daily_times=11:00,17:30
}

=head1 CONTRIBUTING

TODO

=head1 License

MIT

=cut
