#!/usr/bin/env perl

#  Author: Nicholas Hubbard
#  Email:  nicholashubbard@posteo.net
#  WWW:    https://github.com/NicholasBHubbard/yabsm
#
#  Installation script for yabsm and yabsmd. Installation of yabsm is as
#  simple as figuring out where to put the files in yabsms 'export' directory.

use strict;
use warnings;
use v5.16.3;

use File::Copy;
use File::Basename qw/basename dirname/;

use Getopt::Long qw/:config bundling no_ignore_case no_auto_abbrev/;

my $script = basename(__FILE__);
my $yabsm_root = dirname(abs_path(__FILE__ . '/..'));

my $usage = <<END_USAGE;
Usage: $script [-y dir | -d dir]

Arguments:
  -h or --help     Print help (this message) and exit
  -y <dir>         Install yabsm to <dir> - defaults to /usr/local/bin
  -d <dir>         Install yabsmd to <dir> - defaults to /usr/local/sbin
END_USAGE

my $help;
my $yabsm_install_dir = '/usr/local/bin/';
my $yabsmd_install_dir = '/usr/local/sbin/';

GetOptions( 'y=s'    => \$yabsm_install_dir
          , 'd=s'    => \$yabsmd_install_dir
          , 'help|h' => \$help
          ) or die $usage;

print $usage and exit 0 if $help;

my $export_dir = "$yabsm_root/export";

copy "$export_dir/yabsmd.conf.example", '/etc' or die "$script: error: $!\n";
copy "$export_dir/yabsm.fatpack.pl", "$yabsm_install_dir/yabsm" or die "$script: error: $!\n";
copy "$export_dir/yabsmd.fatpack.pl", "$yabsmd_install_dir/yabsmd" or die "$script: error: $!\n";

say 'all good';
