.TH "YABSM" "1" "August 2021" "YABSM" "YABSM User Guide"
.SH "NAME"
yabsm \- btrfs snapshot manager

.SH "SYNOPSIS"
.B yabsm
[\fB\-f\fR \fI?SUBVOL ?QUERY\fR]
[\fB\-b\fR \fIBACKUP\fR]
[\fB\-k\fR \fIBACKUP\fR]
[\fB\-s\fR \fISUBVOL CATEGORY\fR]

      [\fB\-c\fR \fI?CONFIG\fR]
[\fB\-u\fR]
[\fB\-C\fR]
[\fB\-h\fR]
[\fB\-\-test\-remote\-backup \fIBACKUP\fR]

.SH "OPTIONS"
Use exactly one of the following options:
.TP
.BR \-\-find ", " \-f\ \fI?SUBJECT\ ?QUERY\fR
Find a snapshot of ?SUBJECT that matches ?QUERY. Both the subvol and
query arguments are optional, and can be passed in different order. If
these arguments are omitted the user (you) will be prompted for
them. ?SUBJECT can be any subvol or backup defined in /etc/yabsmrc.
.TP
.BR \-\-check\-config ", " \-c\ \fI?CONFIG\fR
Check that ?CONFIG is a valid yabsm configuration file. If errors are
found they be printed to STDERR and the program will exit with a
non-zero status. If the config is valid print 'all good' to stdout. If
the ?CONFIG argument is omitted then /etc/yabsmrc is checked.
.TP
.BR \-\-update\-crontab ", " \-u
Read /etc/yabsmrc and write the proper cronjobs to /etc/crontab for
taking snapshots. This is a root only option.
.TP
.BR \-\-print\-crons ", " \-C
Print the cronjob strings that would be written to /etc/crontab if the
\-\-update\-crontab option were used. This is useful if the user wants
to write yabsm cronjobs to a file other than /etc/crontab.
.TP
.BR \-\-take\-snap ", " \-s\ \fISUBVOL\ TIMEFRAME\fR
Take a new snapshot of SUBVOL and insert it into the directory
for TIMEFRAME. It is not recommended to use this option manually,
and should probably only be used in cronjobs. This is a root only
option.
.TP
.BR \-\-do\-backup ", " \-b\ \fIBACKUP\fR
Perform an incremental backup for BACKUP. BACKUP must be a defined
backup in the users /etc/yabsmrc. If the bootstrap phase of the
incremental backup has not yet happened then the bootstrap phase is
performed and the program exits. It is not recommended to use this
option manually, and should probably only be used in cronjobs. Please
see the btrfs documentation on incremental backups for more
information. This is a root only option.
.TP
.BR \-\-bootstrap\-backup ", " \-k\ \fIBACKUP\fR
Perform the bootstrap phase of a btrfs incremental backup for
BACKUP. BACKUP must be a defined backup in /etc/yabsmrc. It may be
helpful to run this command every so often make incremental backups
faster. Please see the btrfs documentation on incremental backups for more
information. This is a root only option.
.TP
.BR \-\-test\-remote\-backup\ \fIBACKUP\fR
Test that the remote backup BACKUP is configured correctly. Correct
configuration means that we can connect to BACKUP's remote host, and
use the btrfs command with sudo without needing to enter any
passwords.
.TP
.BR \-\-help ", " \-h
Display basic help information.

.SH "CONFIGURATION"

Yabsm is configured through the /etc/yabsmrc file. On installation the
user is given a default template configuration. 

.SH "FIND"
The \fB\-\-find\fR option is used to find one or more snapshots of a
subject by applying a query to all of the subjects snapshots. A subject
can be any subvol or backup defined in /etc/yabsmrc. If multiple snapshots
are found they are printed to stdout sorted from newest to oldest.

.SS "EXAMPLES:"

Assume that the user has a subvol called \fIhome\fR and a backup
called \fIhomeBackup\fR.

\(bu yabsm -f home all

\(bu yabsm -f homeBackup newest

\(bu yabsm -f home oldest

\(bu yabsm -f homeBackup back-10-hours

\(bu yabsm -f homeBackup 12-25

\(bu yabsm -f b-10-h home

\(bu yabsm -f homeBackup back-10-days

\(bu yabsm -f home 'before b-10-mins'

\(bu yabsm -f home 'after b-10-mins'

\(bu yabsm -f homeBackup 'after 2021-12-25-23-59'

\(bu yabsm -f home 'between b-10-d 12-25'

\(bu yabsm -f home 'between 12-25 b-10-d'

.SS "QUERY STRUCTURE:"

There are three different kinds of queries. A \fBconstant\fR query, an
\fBimmediate\fR query and a \fBkeyword\fR query.

\fBConstant Queries\fR

    \(bu all    - return all the snapshots of subject.
    
    \(bu newest - return the newest snapshot of subject.
    
    \(bu oldest - return the oldest snapshot of subject.

\fBImmediate Queries\fR

    An immediate query gives the one snapshot of the subject that is closest
    to the time denoted by the immediate.

    An immediate can be either a \fIrelative\fR time or a \fIliteral\fR time.

    A \fIrelative\fR time is a time relative to the current system
    time when the yabsm program is invoked. Relative times have the form
    \fBback-amount-unit\fR. \fIback\fR can always be abbreviated to
    \fIb\fR. \fIamount\fR must be an integer greater than or equal to
    zero. \fIunit\fR is a time unit that can be either \fIminutes\fR,
    \fIhours\fR, or \fIdays\fR. Time units can be abbreviated
    intuitively to \fImins\fR, \fIm\fR, \fIhrs\fR, \fIh\fR, \fId\fR.

    A \fIliteral\fR time comes in one of 5 forms:

        \(bu yr-mon-day-hr-min

        \(bu yr-mon-day

        \(bu mon-day

        \(bu mon-day-hr

        \(bu mon-day-hr-min

    The first form \fIyr-mon-day-hr-min\fR is the base form. All other
    forms are a shorthand of this form. The shorthand rules are simple. If the
    \fIyr\fR field is omitted then we assume the current year. If
    either the \fIhr\fR or \fImin\fR fields are omitted then they are
    inferred to be zero. So if the year is 2020 the \fIimmediate\fR
    time \fB12-25\fR is the same as \fB2020-12-25-0-0\fR.

\fBKeyword Queries\fR

    A \fIkeyword\fR query is a query that takes \fIimmediate\fRs as arguments.
    There are three different kinds of \fIkeyword\fR queries. The terms delimited
    by \fB|\fR are equivalent.

        \(bu after   | aft | newer

        \(bu before  | bef | older

        \(bu between | bet

    An \fBafter\fR query takes one immediate argument and matches all the
    snapshots taken after the time denoted by the immediate. 
    
    A \fBbefore\fR query takes one immediate argument and matches all the
    snapshots taken before the time denoted by the immediate.

    A \fBbetween\fR query takes two immediate arguments and matches all
    snapshots taken between (inclusive) the times denoted by the immediates. It
    does not matter what order you pass the two immediates.

.SH "CONFIGURATION"
TODO

.SH "AUTHOR"
Written by Nicholas Hubbard

.SH "REPORTING BUGS"
Please report bugs at 
.UR https://github.com/NicholasBHubbard/yabsm/issues
.UE .

.SH "COPYRIGHT"
Copyright (c) 2021 Nicholas Hubbard

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
